spring:
  thymeleaf:
  redis:
    host: 211.178.235.51
    port: 6379
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: admin
    url: jdbc:mysql://booker.cqjw1iajcspu.ap-northeast-2.rds.amazonaws.com:3306/booker
    password: qlgodrl12
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: com.sparta.booker.domain.search.querydsl.config.MySQL8DialectCustom
        show_sql: false
        format_sql: false
  kafka:
    bootstrap-servers: 3.38.35.127:9092, 3.38.35.127:9093, 3.38.35.127:9094
    consumer:
      bootstrap-servers: 3.38.35.127:9092, 3.38.35.127:9093, 3.38.35.127:9094
      group-id: bookGroup
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.LongDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
    producer:
      bootstrap-servers: 3.38.35.127:9092, 3.38.35.127:9093, 3.38.35.127:9094
      key-serializer: org.apache.kafka.common.serialization.LongSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
  servlet:
    multipart:
      max-request-size: 1500MB
      max-file-size: 1500MB
  devtools:
    livereload:
      enabled : true
  data:
    web:
      pageable:
        default-page-size: 10
#logging:
#  config: classpath:logback-spring.xml
#  port: 8080
#  level:
#    org:
#      springframework:
#        data:
#          elasticsearch:
#            client:
#              WIRE:
#                TRACE
#        security: trace
#        web: trace
#      hibernate: info

elasticsearch:
  password: ENC(/9flL9rLmhBk7KhRh3Cl79mJH2Ig5QGnqBkZMxbsufE=)
  username: elastic
  url: 15.165.217.41:9200

jwt:
  secret:
    key: 7ZWt7ZW0OTntmZTsnbTtjIXtlZzqta3snYTrhIjrqLjshLjqs4TroZzrgpjslYTqsIDsnpDtm4zrpa3tlZzqsJzrsJzsnpDrpbzrp4zrk6TslrTqsIDsnpA=
admin:
  secret:
    key: AAABnvxRVklrnYxKZ0aHgTBcXukeZygoC
