## 로그 찍는 드라이버
#spring:
#  datasource:
#    url: jdbc:log4jdbc:mysql://211.178.235.51:3306/BOOKER
#    username: root
#    password: haha5032
#    driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
# 기본 드라이버
spring:
  redis:
    host: 211.178.235.12
    port: 6379
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ENC(qlJNQTS8l1To7FbGyT6m1A==)
    url: ENC(iaoon0t1k7A1VlZGodTTMa+mSnyroY5tbjeLXAAUTZ+c4TrHHzwyWJw0q7cH563LW9WHTz6q36aZsXPiTAnMrJQwyGnmis9QpBphuummoz5PSeUfHvhzccmlGURro3F4)
    password: ENC(d4B1ht0mxIDZpWTHLvy56wZBaJa/EEm8)
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: com.sparta.booker.domain.search.querydsl.config.MySQL8DialectCustom
        show_sql: false
        format_sql: false
  kafka:
    bootstrap-servers: 3.38.35.127:9092, 3.38.35.127:9093
    consumer:
      bootstrap-servers: 3.38.35.127:9092, 3.38.35.127:9093
      group-id: mysql-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.LongDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
    producer:
      bootstrap-servers: 3.38.35.127:9092, 3.38.35.127:9093
      key-serializer: org.apache.kafka.common.serialization.LongSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
  servlet:
    multipart:
      max-request-size: 1500MB
      max-file-size: 1500MB
#logging:
#  level:
#    org:
#      springframework:
#        security: trace
#        web: trace
#      hibernate: info
elasticsearch:
  password: k0+iJRd99fYhAPRm-VLY
  username: elastic
  url: 15.165.217.41:9200

server:
  port: 8080

redis:
  host: 211.178.235.12
  port: 6379
#logging:
#  config: classpath:logback-spring.xml
jwt:
  secret:
    key: 7ZWt7ZW0OTntmZTsnbTtjIXtlZzqta3snYTrhIjrqLjshLjqs4TroZzrgpjslYTqsIDsnpDtm4zrpa3tlZzqsJzrsJzsnpDrpbzrp4zrk6TslrTqsIDsnpA=
admin:
  secret:
    key: AAABnvxRVklrnYxKZ0aHgTBcXukeZygoC

jasypt:
  pw:
    booker77
